import type { Metadata } from "next";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className="antialiased w-full mx-auto px-4 py-8 bg-black"
    >
      {children}
    </main>
  );
}
